### ISSUE TITLE
Child component does not render properly when setting children via state and updated

### ISSUE THREAD

**Issue by bv90** [smoliver/react-malarquee#1]
Hi, I think I have found an issue, I want to set Malarquee text (children props) by using component state, when I update text state via setState, the text change correctly but not the span size container, so its left blank space, this is my code :
```
import React, { Component } from 'react';
import Malarquee from 'react-malarquee';

class Footer extends Component {
    constructor(props) {
        super(props);
        this.antext = this.props.announce;
    }
    componentWillReceiveProps(nextProps) {
        if(this.antext !== nextProps.announce){
            this.forceUpdate(()=>{console.log('force Update Done')});
        }
    }
    render() {
        return <div className="footer">
                        <div className="runningtext">
                            <Malarquee 
                                hoverToPause={true}
                                rate={80}
                                children={this.props.announce}
                            />
                        </div>
                    </div>
    }
}
export default Footer;
```

Please help, since only this component that implement perfect loop of marquee component out there, thank you

**Comment by smoliver** [comment]
@bv90 not seeing the state ate the moment.  Is it being introduced as a prop into your Footer component?  Or is `this.props.announce` a react component with state?

**Comment by bv90** [comment]
sory this is my component script, setState stand in the parent component which dynamically update announce props, thank you @smoliver

**Comment by smoliver** [comment]
Great, so re-measuring whenever a new prop is received will fix your problem?

**Comment by bv90** [comment]
Yeah, thats maybe help,
what code to re-measuring in Malarquee?

**Comment by smoliver** [comment]
@bv90 I'll update the package asap with the fix.  Thanks for the heads up

**Comment by bv90** [comment]
Oke thanks,
Soon would be great 👍

**Comment by smoliver** [comment]
@bv90 I've published a patch.  Go ahead, upgrade and see if it fixes your issue

**Comment by bv90** [comment]
I have update from npm but still got react-malarquee@0.0.11, did you published it to npm yet?
and also, I try to replace react-malarquee module from this recently updated git, but still no re-measuring happen, would you pls guide how to debug the re-measuring function utility script?

**Comment by bv90** [comment]
appearantly my workarround is tuning a litle bit your script js, from :
```
{
    key: 'componentDidUpdate',
    value: function componentDidUpdate() {}
}
```
to this :
```
{
    key: 'componentWillReceiveProps',
    value: function componentWillReceiveProps(nxprops) {
        this.measurementCallback();
    }
  }
```

I hope it will be fix soon and ready on npm, thank you

and one more if I may suggest for additional props, that can set the gap between span copies ( 'fill / loop feature' ), it would make this modul perfect, thank you again

**Comment by smoliver** [comment]
@bv90 I made a mistake and didn't build.  Running `yarn build` or `npm run build` on the package will fix the problem (first time npm author mistake).  I've also published [react-malarquee@0.0.13](https://www.npmjs.com/package/react-malarquee?activeTab=versions)

**Comment by bv90** [comment]
I think use componentWillReceiveProps better than componentDidUpdate, since componentDidUpdate triggered every time text sliding, but componentWillReceiveProps only trigger when props changed (best in performance)
I have submit for pull request please take a look, would be nice if it is in your latest npm repo

**Comment by smoliver** [comment]
@bv90 isn't `componentWillReceiveProps` necessarily called before re-rendering with the new props?   In my tests switching it over the `componentWillReceiveProps` is causing jitters when .  This was just a hot fix, but I am going to create a conditional that only re-measures after a change in children.  The current version, though, is doing fairly minimal work in `componentDidUpdate` compared to the re-render

**Comment by smoliver** [comment]
The best way to avoid `componentDidUpdate` would be to invalidate the `<spans>` when new children are received, and use refs, so I will test with that later this week

**Comment by bv90** [comment]
Oke, thank you for your feedback
